DROP DATABASE IF EXISTS informa_mais
CREATE DATABASE informa_mais default character set utf8
CREATE TABLE Endereco (ID_endereco INTEGER NOT NULL AUTO_INCREMENT, cep VARCHAR(10), cidade VARCHAR(10), bairro VARCHAR(20), rua VARCHAR(25), numero VARCHAR(4), PRIMARY KEY(ID_endereco)) Engine=InnoDB
CREATE TABLE Cidadao (ID_cidadao INTEGER NOT NULL AUTO_INCREMENT,ID_endereco INTEGER, nome VARCHAR(30),data_nascimento DATE, telefone VARCHAR(12), email VARCHAR(35), senha VARCHAR(24), PRIMARY KEY(ID_cidadao)) Engine=InnoDB
CREATE TABLE Relato (ID_relato INTEGER NOT NULL AUTO_INCREMENT, ID_cidadao INTEGER, ID_problema INTEGER, ID_funcionario INTEGER, ID_localizacao INTEGER, descricao VARCHAR(100), data DATETIME, status VARCHAR(15), PRIMARY KEY(ID_relato)) Engine=InnoDB
CREATE TABLE Problema (ID_problema INTEGER NOT NULL AUTO_INCREMENT, categoria VARCHAR(20), subcategoria VARCHAR(20) , PRIMARY KEY(ID_problema)) Engine=InnoDB
CREATE TABLE Localizacao (ID_localizacao INTEGER NOT NULL AUTO_INCREMENT, cep VARCHAR(10), rua VARCHAR(25), cidade VARCHAR(15), bairro VARCHAR(20), PRIMARY KEY (ID_localizacao)) Engine=InnoDB
CREATE TABLE Funcionario_publico (ID_funcionario INTEGER NOT NULL AUTO_INCREMENT, nome VARCHAR(30) , orgao_empresa VARCHAR(15),  email_institucional VARCHAR(35), senha VARCHAR(24) , PRIMARY KEY(ID_funcionario)) Engine=InnoDB
ALTER TABLE Cidadao ADD CONSTRAINT FK_Cidadao_Endereco FOREIGN KEY (ID_endereco) REFERENCES Endereco (ID_endereco) ON DELETE CASCADE
ALTER TABLE Relato ADD CONSTRAINT FK_Relato_Cidadao FOREIGN KEY (ID_cidadao) REFERENCES Cidadao (ID_cidadao) ON DELETE CASCADE
ALTER TABLE Relato ADD CONSTRAINT FK_Problema_Relato FOREIGN KEY (ID_problema) REFERENCES Problema (ID_problema) ON DELETE CASCADE
ALTER TABLE Relato ADD CONSTRAINT FK_Funcionario_Relato FOREIGN KEY (ID_funcionario) REFERENCES Funcionario_publico (ID_funcionario) ON DELETE CASCADE
ALTER TABLE Relato ADD CONSTRAINT FK_Localizacao_Relato FOREIGN KEY (ID_localizacao) REFERENCES Localizacao (ID_localizacao) ON DELETE CASCADE
INSERT INTO relato(descricao, status) VALUES ('buraco na via', 'PUBLICADO'), ('Lixo entulhado', 'EM ANDAMENTO'), ('sem faixa de pedestres', 'DESATIVADO'), ('incendio constante na mata', 'EM ANDAMENTO'), ('Cano estourado jorrando agua', 'RESOLVIDO'), ('luzes do poste piscando', 'PUBLICADO'), ('Capim ocupando estrada', 'DESATIVADO')
INSERT INTO CIDADAO(nome, data_nascimento, telefone, email, senha) VALUES('josney', '2005-04-10', '11111111111', 'josney@gmail.com', 'josney01'), ('adalberto', '1985-01-01', '22222222222', 'adalberto@gmail.com', 'adalberto01'), ('rebeca', '1968-12-15', '33333333333', 'rebeca@gmail.com', 'rebeca01'), ('josefina', '2012-04-30', '44444444444', 'josefina@gmail.com', 'josefina01'), ('samuel', '1993-07-15', '55555555555', 'samuel@gmail.com', 'samuel01'), ('pedro', '2000-06-17', '66666666666', 'pedro@gmail.com', 'pedro01'), ('isabel', '1989-07-28', '77777777777', 'isabel@gmail.com', 'isabel01')
insert into problema(categoria, subcategoria) values ('Vias Publicas', 'Buraco Nas vias'), ('Limpeza e Conservacao', 'Remocao de Entulhos'), ('Mobilidade Urbana', 'Ausencia de faixa de pedestres'), ('Meio Ambiente', 'Queimadas'), ('Agua e Esgoto', 'Vazamento de Agua'), ('Iluminacao e Energia', 'Iluminacao insuficiente'), ('Limpeza e Conservacao', 'Capim alto')
insert into localizacao(cep, cidade, bairro, rua) values ('01011100', 'JooJ', 'Irineu', 'Voce nao sabe nem eu'), ('46578951', 'Sucupira', 'Porto de Galos', 'Almeida Peixoto'), ('78495267', 'Macarana', 'Macaraiba', 'Macarena'), ('48795324', 'Paris', 'Principado', 'Parque das Princesas'), ('19756842', 'Transilvania', 'Fonte Nova', 'Pedro da Alfandega'), ('458795412', 'Atlantida', 'Afogados', 'Poseidon Oliveira'), ('45789555', 'Surubim', 'Mortadela', 'Frederico Amorim')
insert into endereco(cep, cidade, bairro, rua, numero) values ('78495267', 'Macarana', 'Macaraiba', 'Macarena', '742'), ('45789555', 'Surubim', 'Mortadela', 'Frederico Amorim', '551'), ('01011100', 'JooJ', 'Irineu', 'Voce nao sabe nem eu', '521'), ('46578951', 'Sucupira', 'Porto de Galos', 'Almeida Peixoto', '675'), ('458795412', 'Atlantida', 'Afogados', 'Poseidon Oliveira', '467'), ('19756842', 'Transilvania', 'Fonte Nova', 'Pedro da Alfandega', '139'), ('48795324', 'Paris', 'Principado', 'Parque das Princesas', '875')
INSERT INTO funcionario_publico(nome, orgao_empresa, email_institucional, senha) values ('Edivaldo', 'Celpe', 'EdivaldoPericleito@Rasta.com', 'Rastamafire'), ('Josney Silva', 'Compesa', 'Josney@hotney.com', 'silvajosney'), ('Leno Guissa', 'Compesa', 'LenGuissa@toscana.com', '12345678'), ('JooJ', 'Prefeitura', 'JooJ@JeeJ.com', 'JuuJ1234'), ('Irineu', 'Compesa', 'VCnSabe@Nem.EU', 'senha'), ('Alborghetti', 'Prefeitura', 'EuNumTo@Loko.com', 'Capivara123'), ('Bambam', 'Celpe', 'Birl@BodyBuilder.com', 'trapezioDescendente897')
